#! /usr/bin/env bash

set -eu -o pipefail

#
# delete-web-acl
#
# delete-web-acl deletes a Web ACL and first clears the associations and removes all the rules from the acl.
#

function usage() {
  echo "Usage: ${0##*/} <web-acl-id>"
  exit 1
}

if [[ $# -ne 1 ]]; then
  usage
fi

webAclId=$1

if ! command -v aws &> /dev/null; then
  echo "error: aws not installed, please install AWS CLi" 1>&2
  exit 1
fi

if ! command -v jq &> /dev/null; then
  echo "error: jq not installed, please install JQ" 1>&2
  exit 1
fi

echo "Deleting ACL ${webAclId}"

echo "Current Web ACL"
webAcl=$(aws waf-regional get-web-acl --web-acl-id "${webAclId}" | jq -cr .)
echo "${webAcl}" | jq .

# shellcheck disable=SC2207
resources=($(aws waf-regional list-resources-for-web-acl --web-acl-id "${webAclId}" | jq -r ".ResourceArns[]"))
echo "Current Associations"
echo "${resources[@]:-None}" | tr ' ' '\n'
echo ""

for resource in "${resources[@]}"; do
  echo "Disassociating resource ${resource}"
  aws waf-regional disassociate-web-acl --resource-arn "${resource}"
done

echo ""

# shellcheck disable=SC2207
rules=($(aws waf-regional get-web-acl --web-acl-id "${webAclId}" | jq -c ".WebACL.Rules[]" ))
echo "Current Rules"
echo "${rules[@]:-None}" | tr ' ' '\n'
echo ""

for rule in "${rules[@]}"; do
  echo "Removing rule ${rule}"
  id=$(echo "${rule}" | jq -r .RuleId)
  priority=$(echo "${rule}" | jq -r .Priority)
  actionType=$(echo "${rule}" | jq -r .Action.Type)
  type=$(echo "${rule}" | jq -r .Type)

  echo "Using change token"
  CHANGE_TOKEN=$(aws waf-regional get-change-token | jq -r .ChangeToken)
  echo "${CHANGE_TOKEN}"

  # shellcheck disable=SC2026,SC1083
  updates=Action='"'DELETE'"',ActivatedRule={Priority=${priority},RuleId='"'${id}'"',Action={Type='"'${actionType}'"'},Type='"'${type}'"'}
  aws waf-regional update-web-acl --web-acl-id "${webAclId}" --change-token "${CHANGE_TOKEN}" --updates "${updates}" > /dev/null

done

echo "Using change token"
CHANGE_TOKEN=$(aws waf-regional get-change-token | jq -r .ChangeToken)
echo "${CHANGE_TOKEN}"

echo "Deleting web acl"
aws waf-regional delete-web-acl --web-acl-id "${webAclId}" --change-token "${CHANGE_TOKEN}" > /dev/null

echo "Done"
